name: Bug Fix Pull Request
description: Implement a bug fix to help us improve.
title: "[Bug] "
labels: [ "bug" ]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: |
        Please check that you have done the following things before submitting an issue.
      options:
        - label: I confirm that I have [searched for existing issues](https://github.com/Xujiayao/MCDiscordChat/issues?q=is%3Aissue) before reporting to avoid duplicate reporting.
          required: true
  - type: input
    id: related_issues
    attributes:
      label: Related Issues
      description: |
        Any GitHub issues related to this PR? If not, please fill in N/A.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please tell us what bug have you fixed with a clear and detailed description, add screenshots to help explain.
    validations:
      required: true