name: Bug Report
description: Create a report to help us improve.
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "**Note: Please search for existing issues before reporting where possible to avoid duplicate reporting.**"
  - type: checkboxes
    id: simplest_environment_tested
    attributes:
      label: Simplest Environment Tested
      options:
        - label: I confirm that this problem still exists with only MCDiscordChat and Fabric API installed.
          required: true
  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft Version
      description: |
        The version of Minecraft you are using?
    validations:
      required: true
  - type: input
    id: mcdiscordchat_version
    attributes:
      label: MCDiscordChat Version
      description: |
        The version of MCDiscordChat you are using?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please tell us what the bug is with a clear and detailed description, add screenshots to help explain if possible.
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: To Reproduce
      description: |
        How do you trigger this bug? Please walk us through it step by step.
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log
      description: |
        Please provide your full log here.
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Config
      description: |
        Please provide your MCDiscordChat config file (mcdiscordchat.json) here, remember to remove the botToken and webhookURL.
    validations:
      required: true