name: Feature Request
description: Suggest an idea for this project.
title: "[Enhancement] "
labels: ["enhancement"]
body:
  - type: checkboxes
    id: existing_issues_searched
    attributes:
      label: Existing Issues Searched
      options:
        - label: I confirm that I have [searched for existing issues](https://github.com/Xujiayao/MCDiscordChat/issues?q=is%3Aissue) before reporting to avoid duplicate reporting.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What new feature or change do you want? What does it improve? Please tell us what the new feature or change is with a clear and detailed description, add screenshots to help explain if possible.
    validations:
      required: true