name: Question
description: Anything you don't understand.
title: "[Question] "
labels: ["question"]
body:
  - type: checkboxes
    id: existing_issues_searched
    attributes:
      label: Existing Issues Searched
      options:
        - label: I confirm that I have [searched for existing issues](https://github.com/Xujiayao/MCDiscordChat/issues?q=is%3Aissue) before reporting to avoid duplicate reporting.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please tell us what the question is with a clear and detailed description, add screenshots to help explain if possible.
    validations:
      required: true